language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

deploy:
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: seob_example
    deployment_group: seob_example
    region: ap-northeast-2